### ISSUE TITLE
Anchor problem

### ISSUE THREAD

**Issue by doreybenjamin** [AntoineW/luge#20]
Hi,
Thanks for this very cool tool!
I use Smooth scroll but i have problem with anchor, i saw your help for # links here : https://luge.cool/docs/use-hash-links-with-transitions/ but i have error : 
"error  Parsing error: Unexpected token {" 
i not use JS framework.

any tips ? 

thx :)

**Comment by AntoineW** [comment]
Hi,
Could you share the code you wrote to do that?

**Comment by doreybenjamin** [comment]
This is your code : 
luge.lifecycle.add('pageIn', this.navigateToTarget.bind(this))

navigateToTarget (done) {
  const hash = window.location.hash
  if (hash) {
    const target = document.querySelector(hash)
    if (target) {
      window.scrollTo(0, target.getBoundingClientRect().top)
    }
  }

  done()
}

**Comment by AntoineW** [comment]
Ok, but where do you use that? Can you show the rest of your file?

The code above has to be used inside a class, otherwise you should write it like that:
```js
luge.lifecycle.add('pageIn', navigateToTarget)

function navigateToTarget (done) {
  const hash = window.location.hash
  if (hash) {
    const target = document.querySelector(hash)
    if (target) {
      window.scrollTo(0, target.getBoundingClientRect().top)
    }
  }

  done()
}
```

**Comment by doreybenjamin** [comment]
This is why i have a error, it is paste in my js files juste like this...
What is the right writing without class ?

**Comment by AntoineW** [comment]
I wrote it in my message above 🤔

**Comment by doreybenjamin** [comment]
oh i see the difference right know sorry, i check later :)

**Comment by doreybenjamin** [comment]
Ok that works for anchor that points to another page but when the anchor is in the same page not yet !

**Comment by doreybenjamin** [comment]
Yes working !

**Comment by AntoineW** [comment]
Good! The new 0.6.7-beta version containing that fix is available.

**Comment by doreybenjamin** [comment]
@AntoineW (j'en ai marre de te faire souffrir avec mon anglais :p) j'ai trouvé un dernier truc, c'est sur Firefox, lien externe avec anchor si tu redimensionnes la page et que tu refais la manip cela remonte la page, si tu veux, je peux te montrer sur un de mes sites en dev en mp.
