### ISSUE TITLE
"Could not find a declaration file for module '@waaark/luge'

### ISSUE THREAD

**Issue by kaba992** [AntoineW/luge#21]
Bonjour Antoine,
Tout d'abord merci pour pour Luge!
Je suis de débutant qui test des trucs avec Luge je m'amuse beaucoup!
j'ai essayé de l'installer via npm mais j'ai ce problème:
voici l'erreur
```
 "Could not find a declaration file for module '@waaark/luge'. 'E:/32bits/32_bits/node_modules/@waaark/luge/dist/js/luge.esm.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/waaark__luge` if it exists or add a new declaration (.d.ts) file containing `declare module '@waaark/luge';`ts(7016)ç"
```
Merci de ton aide :)
Dernière petite suggestion, se  serait hyper cool pour les débutants d'avoir des exemples sur codepen comme tu l'as fait avec le custom cursor:
j'essaye de faire des transitions et des preloaders avec des lotties mais il ne se passe rien je n'ai aucune référence sur le web pour m'aider.
Je sais que ça prend beaucoup de temps mais un jour pourquoi pas :).
Merci encore!

**Comment by AntoineW** [comment]
Hello et merci 🙏
On dirait que tu essayes d'utiliser luge en TypeScript ? Je n'ai jamais essayé mais je ne suis pas sur que ça marche.
Tu peux peut-être essayer d'ignorer l'erreur en utilisant [`// @ts-ignore`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#suppress-errors-in-ts-files-using--ts-ignore-comments)

**Comment by kaba992** [comment]
Merci de ta réponse!
Au final j'ai mis directement le js et css dans min projet.
Pour les animations de preloader et transitions de pages, je suis tout comme indiqué dans la doc, et au moment de la transition il nz se passe rien y a t-il des trucs à faire côté javascript ?
J'utilise une animation json 
Merci encore de ton aide :)

**Comment by AntoineW** [comment]
Là comme ça c'est dur à dire, tu peux partager ton code?

**Comment by kaba992** [comment]
![image](https://user-images.githubusercontent.com/89903118/161716455-7852f94c-4d22-4986-a1d7-fbe7158e7a14.png)
![image](https://user-images.githubusercontent.com/89903118/161716621-9a16d874-e4ce-4eef-a959-55d019cc42ea.png)
Voilà 
Merci encore de ton aide

**Comment by AntoineW** [comment]
Est-ce que tu as une erreur dans la console ? C'est peut être le chemin vers le fichier JSON qui n'est pas bon, tu as essayé sans le `/` ?

**Comment by kaba992** [comment]
![image](https://user-images.githubusercontent.com/89903118/161725341-637df882-974a-4ca5-a947-fb710852e60e.png)
j'ai enlevé le / et je n'ai aucune erreur dans la console.
il suffit juste de mettre
`<div data-lg-preloader="lottie" data-lg-preloader-in="99274-loading.json"></div>`
et `luge.settings({ preloader: { duration: 8 } })`?
Je l'ai pris là mon lottie si ça peut aider.
Merci encore j'aimerais trop que ça marche j'adore Luge :)

**Comment by AntoineW** [comment]
Le preloader lottie n'est pas prévu pour afficher un loader comme ça, c'est plutôt pensé pour faire quelque chose comme ça https://legacy.waaark.com, où l'animation lottie remplie tout l'écran.

Dans ton cas, pour avoir un loader au centre de l'écran, il faut plutôt le faire comme ça https://codepen.io/wodniack/pen/yLpGdVW

**Comment by kaba992** [comment]
Déjà chapeau pour ce magnifique site https://legacy.waaark.com/!
J'ai fait exactement la même chose que toi maintenant j'ai bien un fond clair qui dure 5 sec quand je rafraichis mais pas d'animation ):.
J'ai réessayé d'installer luge via npm mais toujours ce problème:

![luge](https://user-images.githubusercontent.com/89903118/163960389-c45fac35-c4fa-4591-92c7-7fc148025180.png)
Merci encore de ton aide @AntoineW

**Comment by AntoineW** [comment]
Tu as bien chargé lottie aussi en amont ? Ce n'est pas intégré dans luge, tu dois le charger à part https://github.com/airbnb/lottie-web#html-player-installation
