### ISSUE TITLE
great website 

### ISSUE THREAD

**Issue by bacloud23** [AntoineW/luge#32]
I really like the idea of this library so thanks a lot for your valuable work!!!

before starting to use the library itself, I have a question please, how did you make those GIFs in the website itself. it looks super cool . like this one
https://luge.cool/wp-content/themes/luge/static/img/feature-transitions.svg

any tool for this? or hand made? 
thanks!

**Comment by AntoineW** [comment]
Thanks 🤩
It's completely hand made, you can see the code here https://codepen.io/wodniack/pen/poNKaOe

**Comment by bacloud23** [comment]
thanks a lot! again for the code I can move on with something similar. good luck
