### ISSUE TITLE
Missing Math.clamp

### ISSUE THREAD

**Issue by hamburger123456** [AntoineW/luge#40]
You are using Math.clamp() in SmoothScroll & MouseObserver. But the function is not defined in your code.
On https://luge.cool/ you are using a vendor-function clamp().
I implemented this function and it works fine.
function clamp (value, min, max) {
  return Math.max(min, Math.min(max, value))
}
It seems like your code provided here is not the one you are using. 
Math.clamp() is missing.

**Comment by AntoineW** [comment]
Math.clamp() function is part of a new JS feature proposal that is not yet approved. However, it's covered by Babel preset so it should work once the code is compiled.
