### ISSUE TITLE
Is there a method to stop transition if link clicked on current page?

### ISSUE THREAD

**Issue by betawaxx** [AntoineW/luge#49]
For instance, I have two pages 

page one has `data-lg-page="page1"`
page two has `data-lg-page="page2"`

Currently if I click a link for page1 while on page1 the transition plays and reloads that page, I have tried adding a prevent inside an emitter beforePageOut event but its not stopping the transition...

Really enjoying this lib btw!

**Comment by AntoineW** [comment]
Ok, I see the problem. I pushed a new version, 0.6.19-beta, that should fix that. Could you test it and let me know if it works better?
