### ISSUE TITLE
"data-lg-lottie-loop-frame" Attribute Not Working

### ISSUE THREAD

**Issue by jamesathlon** [AntoineW/luge#7]
Hello,

The 'data-lg-lottie-loop-frame' attribute is having no effect on Lottie animations.

Here is the site example:
https://loop-frame.webflow.io/

Thank you for any help in advance, Luge is a fantastic resource.

**Comment by jamesathlon** [comment]
Added site example to the above for debugging.

**Comment by haroldao** [comment]
I think links don't work...

**Comment by AntoineW** [comment]
Same, I can't see the example, but looking at the source code I think it won't work as for now the loop frame attribute only works in conjunction with the reverse attribute. I will change that.

**Comment by jamesathlon** [comment]
@AntoineW 
Sorry for the delay in getting back to you. 
I've tested with the latest version and the loop frames work great!

Thank you for pushing that update!
